---
- hosts: postgres
  vars_files:
    - includes/vars.yaml
  gather_facts: false
  sudo: true
  tasks:
    - name: Install Packates
      include: includes/packages.yaml
    - name: Stop Slave Postgres service
      service: name=postgresql state=stopped
      when: "'pslaves' in group_names"
    - name: Master Setup
      include: includes/master.yaml
      when: "'pmasters' in group_names"
    - name: Slave setup
      include: includes/slave.yaml
      when: "'pslaves' in group_names"
